### ISSUE TITLE
Package dependency issue in baseline

### ISSUE THREAD

**Issue by sonibla** [jordanmontt/RewriteToolsSet#24]
Hello there

Since this morning I get the error `Could not resolve: RewriteCustomRules [RewriteCustomRules]` when trying to load RewriteToolsSet

I think it's because RewriteCustomRules package was removed by commit https://github.com/jordanmontt/RewriteToolsSet/commit/404c14dab3ab865415cf981727350c239b563b89 but is still listed by [BaselineOfRewriteToolsSet](https://github.com/jordanmontt/RewriteToolsSet/blob/master/src/BaselineOfRewriteToolsSet/BaselineOfRewriteToolsSet.class.st)

**Comment by jordanmontt** [comment]
Hello @sonibla Yes, you are right. Keep in mind that I am currently doing some refactors that are breaking the code. So you should not load the master branch. The refactors should be finished by tomorrow. Please load the relase version (v1.0.0)

**Comment by jordanmontt** [comment]
Hello @sonibla I just publish a new stable version of the tool. You should be able to use it now just running the script that is in the README.
